# Build the Cross-Sectional Company Dataset

Valuation date: September 30, 2025. This is a working dataset for initial quality checks, not the final regression sample.

## Load Packages

In [1]:
import pandas as pd
import numpy as np

In [2]:
import os
os.getcwd()

'C:\\Users\\Finn Case\\OneDrive\\Desktop\\Econ 430 Proj 1\\Econ_430_proj_1\\notebooks'

## Load and Inspect Company Data

In [3]:
companies = pd.read_csv("../data/raw/us-companies.zip", sep=";")

In [4]:
companies.head()

  Ticker  SimFinId     Company Name  ...  Market        CIK  Main Currency
0    NaN  20095034              NaN  ...      us  1986247.0            USD
1    NaN  20215308              NaN  ...      us  2033535.0            USD
2    NaN  20619455  CoreWeave, Inc.  ...      us  1769628.0            USD
3    NaN  18692750              NaN  ...      us  1997711.0            USD
4    NaN  18847915              NaN  ...      us  1769731.0            USD

[5 rows x 11 columns]

In [5]:
companies.shape
companies.describe()

           SimFinId     IndustryId  ...  Number Employees           CIK
count  6.593000e+03    6278.000000  ...      5.755000e+03  6.581000e+03
mean   7.131233e+06  104048.265053  ...      7.514445e+03  1.274917e+06
std    6.884316e+06    2818.969285  ...      3.140868e+04  5.286397e+05
min    1.800000e+01  100001.000000  ...      0.000000e+00  0.000000e+00
25%    6.661000e+05  101004.000000  ...      1.360000e+02  9.311480e+05
50%    6.767475e+06  104002.000000  ...      8.800000e+02  1.406234e+06
75%    1.244441e+07  106002.000000  ...      3.700000e+03  1.703157e+06
max    2.080346e+07  111001.000000  ...      1.298000e+06  2.079173e+06

[8 rows x 5 columns]

In [6]:
companies.columns
companies.dtypes
companies.isna().sum()

Ticker                             40
SimFinId                            0
Company Name                       36
IndustryId                        315
ISIN                             1202
End of financial year (month)      35
Number Employees                  838
Business Summary                  299
Market                              0
CIK                                12
Main Currency                       0
dtype: int64

In [7]:
companies.shape

(6593, 11)

In [8]:
companies['IndustryId'].isnull().sum() / companies.shape[0] * 100

np.float64(4.777794630668891)

In [9]:
# IndustryID is a usable column, only 4.8% is null

## Load and Inspect Income Statements

In [10]:
income = pd.read_csv('../data/raw/us-income-quarterly.zip',sep=';')

In [11]:
income.head()

  Ticker  SimFinId  ... Net Income  Net Income (Common)
0      A     45846  ...  288000000            288000000
1      A     45846  ...  216000000            216000000
2      A     45846  ...  264000000            264000000
3      A     45846  ...  442000000            442000000
4      A     45846  ...  283000000            283000000

[5 rows x 28 columns]

In [12]:
income.shape

(47685, 28)

In [13]:
income.columns

Index(['Ticker', 'SimFinId', 'Currency', 'Fiscal Year', 'Fiscal Period',
       'Report Date', 'Publish Date', 'Restated Date', 'Shares (Basic)',
       'Shares (Diluted)', 'Revenue', 'Cost of Revenue', 'Gross Profit',
       'Operating Expenses', 'Selling, General & Administrative',
       'Research & Development', 'Depreciation & Amortization',
       'Operating Income (Loss)', 'Non-Operating Income (Loss)',
       'Interest Expense, Net', 'Pretax Income (Loss), Adj.',
       'Abnormal Gains (Losses)', 'Pretax Income (Loss)',
       'Income Tax (Expense) Benefit, Net',
       'Income (Loss) from Continuing Operations',
       'Net Extraordinary Gains (Losses)', 'Net Income',
       'Net Income (Common)'],
      dtype='str')

In [14]:
income.isnull().sum()

Ticker                                          0
SimFinId                                        0
Currency                                        0
Fiscal Year                                     0
Fiscal Period                                   0
Report Date                                     0
Publish Date                                    0
Restated Date                                   0
Shares (Basic)                                325
Shares (Diluted)                              389
Revenue                                      5100
Cost of Revenue                             10240
Gross Profit                                10230
Operating Expenses                             90
Selling, General & Administrative            2120
Research & Development                      24320
Depreciation & Amortization                 28174
Operating Income (Loss)                         3
Non-Operating Income (Loss)                   491
Interest Expense, Net                        6061
Pretax Income (Loss), Adj.                      2
Abnormal Gains (Losses)                     21595
Pretax Income (Loss)                            0
Income Tax (Expense) Benefit, Net            9844
Income (Loss) from Continuing Operations        0
Net Extraordinary Gains (Losses)            44903
Net Income                                      0
Net Income (Common)                             0
dtype: int64

In [15]:
income = income[[
    'Ticker',
    'SimFinId',
    'Currency',
    'Fiscal Year',
    'Fiscal Period',
    'Report Date',
    'Publish Date',
    'Restated Date',
    'Revenue',
    'Gross Profit',
    'Operating Income (Loss)',
    'Depreciation & Amortization',
    'Interest Expense, Net',
    'Pretax Income (Loss)',
    'Income Tax (Expense) Benefit, Net',
    'Net Income'
]]

## Load and Inspect Balance Sheets

In [16]:
balance = pd.read_csv("../data/raw/us-balance-quarterly.zip",sep=";")

In [17]:
balance.head()

  Ticker  SimFinId  ...  Total Equity  Total Liabilities & Equity
0      A     45846  ...  4.804000e+09                  9674000000
1      A     45846  ...  4.810000e+09                 10398000000
2      A     45846  ...  4.946000e+09                 10491000000
3      A     45846  ...  5.389000e+09                 10705000000
4      A     45846  ...  5.154000e+09                 10327000000

[5 rows x 30 columns]

In [18]:
balance.columns

Index(['Ticker', 'SimFinId', 'Currency', 'Fiscal Year', 'Fiscal Period',
       'Report Date', 'Publish Date', 'Restated Date', 'Shares (Basic)',
       'Shares (Diluted)', 'Cash, Cash Equivalents & Short Term Investments',
       'Accounts & Notes Receivable', 'Inventories', 'Total Current Assets',
       'Property, Plant & Equipment, Net',
       'Long Term Investments & Receivables', 'Other Long Term Assets',
       'Total Noncurrent Assets', 'Total Assets', 'Payables & Accruals',
       'Short Term Debt', 'Total Current Liabilities', 'Long Term Debt',
       'Total Noncurrent Liabilities', 'Total Liabilities',
       'Share Capital & Additional Paid-In Capital', 'Treasury Stock',
       'Retained Earnings', 'Total Equity', 'Total Liabilities & Equity'],
      dtype='str')

In [19]:
balance.isnull().sum()

Ticker                                                 0
SimFinId                                               0
Currency                                               0
Fiscal Year                                            0
Fiscal Period                                          0
Report Date                                            0
Publish Date                                           0
Restated Date                                          0
Shares (Basic)                                       322
Shares (Diluted)                                     386
Cash, Cash Equivalents & Short Term Investments      164
Accounts & Notes Receivable                         9934
Inventories                                        21612
Total Current Assets                                   5
Property, Plant & Equipment, Net                    3237
Long Term Investments & Receivables                36634
Other Long Term Assets                              1564
Total Noncurrent Assets                              303
Total Assets                                           0
Payables & Accruals                                  158
Short Term Debt                                    22711
Total Current Liabilities                             58
Long Term Debt                                     13260
Total Noncurrent Liabilities                        1380
Total Liabilities                                      9
Share Capital & Additional Paid-In Capital           652
Treasury Stock                                     31523
Retained Earnings                                   1882
Total Equity                                           5
Total Liabilities & Equity                             0
dtype: int64

In [20]:
balance = balance[[
    'Ticker',
    'SimFinId',
    'Currency',
    'Fiscal Year',
    'Fiscal Period',
    'Report Date',
    'Publish Date',
    'Restated Date',
    'Cash, Cash Equivalents & Short Term Investments',
    'Short Term Debt',
    'Long Term Debt',
    'Total Assets',
    'Total Liabilities',
    'Total Equity'
]]

## Load and Inspect Cash Flow Statements

In [21]:
cashflow = pd.read_csv(
    "../data/raw/us-cashflow-quarterly.zip",
    sep=";"
)

In [22]:
cashflow.shape

(47687, 28)

In [23]:
cashflow.head()

  Ticker  SimFinId  ... Net Cash from Financing Activities  Net Change in Cash
0      A     45846  ...                       -316000000.0          -111000000
1      A     45846  ...                        166000000.0            51000000
2      A     45846  ...                       -222000000.0            48000000
3      A     45846  ...                       -324000000.0            55000000
4      A     45846  ...                       -546000000.0          -371000000

[5 rows x 28 columns]

In [24]:
cashflow.columns

Index(['Ticker', 'SimFinId', 'Currency', 'Fiscal Year', 'Fiscal Period',
       'Report Date', 'Publish Date', 'Restated Date', 'Shares (Basic)',
       'Shares (Diluted)', 'Net Income/Starting Line',
       'Depreciation & Amortization', 'Non-Cash Items',
       'Change in Working Capital', 'Change in Accounts Receivable',
       'Change in Inventories', 'Change in Accounts Payable',
       'Change in Other', 'Net Cash from Operating Activities',
       'Change in Fixed Assets & Intangibles',
       'Net Change in Long Term Investment',
       'Net Cash from Acquisitions & Divestitures',
       'Net Cash from Investing Activities', 'Dividends Paid',
       'Cash from (Repayment of) Debt', 'Cash from (Repurchase of) Equity',
       'Net Cash from Financing Activities', 'Net Change in Cash'],
      dtype='str')

In [25]:
cashflow.isna().sum()

Ticker                                           0
SimFinId                                         0
Currency                                         0
Fiscal Year                                      0
Fiscal Period                                    0
Report Date                                      0
Publish Date                                     0
Restated Date                                    0
Shares (Basic)                                 325
Shares (Diluted)                               389
Net Income/Starting Line                       457
Depreciation & Amortization                   2503
Non-Cash Items                                 484
Change in Working Capital                      413
Change in Accounts Receivable                47242
Change in Inventories                        47367
Change in Accounts Payable                   47296
Change in Other                              47076
Net Cash from Operating Activities               4
Change in Fixed Assets & Intangibles          4120
Net Change in Long Term Investment           30691
Net Cash from Acquisitions & Divestitures    32054
Net Cash from Investing Activities            1548
Dividends Paid                               30857
Cash from (Repayment of) Debt                12387
Cash from (Repurchase of) Equity             11052
Net Cash from Financing Activities            1040
Net Change in Cash                               0
dtype: int64

In [26]:
cashflow = cashflow[
    [
        'Ticker',
        'SimFinId',
        'Currency',
        'Fiscal Year',
        'Fiscal Period',
        'Report Date',
        'Publish Date',
    'Restated Date',
        'Net Income/Starting Line',
        'Depreciation & Amortization',
        'Net Cash from Operating Activities',
        'Change in Fixed Assets & Intangibles',
        'Net Cash from Investing Activities',
        'Cash from (Repayment of) Debt',
        'Net Cash from Financing Activities',
        'Net Change in Cash'
    ]
]

## Load and Inspect Share Prices

In [27]:
prices = pd.read_csv(
    "../data/raw/us-shareprices-daily.zip",
    sep=";"
)

In [28]:
prices.shape

(6217940, 11)

In [29]:
prices.columns

Index(['Ticker', 'SimFinId', 'Date', 'Open', 'High', 'Low', 'Close',
       'Adj. Close', 'Volume', 'Dividend', 'Shares Outstanding'],
      dtype='str')

In [30]:
prices.head()

  Ticker  SimFinId        Date  ...   Volume  Dividend  Shares Outstanding
0      A     45846  2020-11-05  ...  1143082       NaN         306000000.0
1      A     45846  2020-11-06  ...  1036556       NaN         306000000.0
2      A     45846  2020-11-09  ...  2178042       NaN         306000000.0
3      A     45846  2020-11-10  ...  2124829       NaN         306000000.0
4      A     45846  2020-11-11  ...  1792823       NaN         306000000.0

[5 rows x 11 columns]

In [31]:
prices.isna().sum()

Ticker                    816
SimFinId                    0
Date                        0
Open                        0
High                        0
Low                         0
Close                       0
Adj. Close                  0
Volume                      0
Dividend              6180595
Shares Outstanding     438299
dtype: int64

In [32]:
prices['Date'].min()

'2020-11-05'

In [33]:
prices['Date'].max()

'2025-10-09'

In [34]:
prices['Date'].dtype

## Convert Date Columns

In [35]:
prices['Date'] = pd.to_datetime(prices['Date'])

In [36]:
prices['Date'].dtype

dtype('<M8[us]')

In [37]:
income['Report Date'] = pd.to_datetime(income['Report Date'])
income['Publish Date'] = pd.to_datetime(income['Publish Date'])

balance['Report Date'] = pd.to_datetime(balance['Report Date'])
balance['Publish Date'] = pd.to_datetime(balance['Publish Date'])

cashflow['Report Date'] = pd.to_datetime(cashflow['Report Date'])
cashflow['Publish Date'] = pd.to_datetime(cashflow['Publish Date'])
income['Restated Date'] = pd.to_datetime(income['Restated Date'])
balance['Restated Date'] = pd.to_datetime(balance['Restated Date'])
cashflow['Restated Date'] = pd.to_datetime(cashflow['Restated Date'])

In [38]:
income['Publish Date'].min(), income['Publish Date'].max()

(Timestamp('2009-01-01 00:00:00'), Timestamp('2026-07-17 00:00:00'))

In [39]:
balance['Publish Date'].min(), balance['Publish Date'].max()

(Timestamp('2009-01-01 00:00:00'), Timestamp('2026-07-17 00:00:00'))

In [40]:
cashflow['Publish Date'].min(), cashflow['Publish Date'].max()

(Timestamp('2009-01-01 00:00:00'), Timestamp('2026-07-17 00:00:00'))

In [41]:
prices['Date'] = pd.to_datetime(prices['Date'])

## Select the Valuation Date

In [42]:
valuation_date = pd.Timestamp('2025-09-30')
freshness_cutoff = pd.Timestamp('2024-09-30')

In [43]:
prices_on_date = prices[prices['Date'] == valuation_date]

In [44]:
prices_on_date = prices[prices['Date'] == valuation_date]

prices_on_date.shape

(4699, 11)

In [45]:
prices_on_date['SimFinId'].nunique()

4699

In [46]:
prices_on_date['Shares Outstanding'].isna().sum()

np.int64(178)

In [47]:
prices_on_date['Shares Outstanding'].notna().sum()

np.int64(4521)

In [48]:
prices_on_date[
    ['Ticker', 'SimFinId', 'Close', 'Shares Outstanding']
].head(10)

      Ticker  SimFinId   Close  Shares Outstanding
1229       A     45846  128.35        2.835004e+08
2466      AA    367153   32.89        2.589147e+08
2595    AACB  18959140   10.18                 NaN
3828    AACG  18712193    1.38        6.399578e+07
6332    AAGH  12444287    0.00        2.120481e+10
8351     AAL     68568   11.24        6.598288e+08
8619     AAM  18508049   10.52        4.397400e+07
10826   AAME    450021    2.87        2.039723e+07
13032   AAOI    671827   25.93        6.235385e+07
14269   AAON    919501   93.44        8.153068e+07

In [49]:
prices_on_date['Shares Outstanding'].isna().sum()

np.int64(178)

In [50]:
prices_on_date['Shares Outstanding'].notna().sum()

np.int64(4521)

In [51]:
prices_on_date[
    ['Ticker', 'SimFinId', 'Close', 'Shares Outstanding']
].head(10)

      Ticker  SimFinId   Close  Shares Outstanding
1229       A     45846  128.35        2.835004e+08
2466      AA    367153   32.89        2.589147e+08
2595    AACB  18959140   10.18                 NaN
3828    AACG  18712193    1.38        6.399578e+07
6332    AAGH  12444287    0.00        2.120481e+10
8351     AAL     68568   11.24        6.598288e+08
8619     AAM  18508049   10.52        4.397400e+07
10826   AAME    450021    2.87        2.039723e+07
13032   AAOI    671827   25.93        6.235385e+07
14269   AAON    919501   93.44        8.153068e+07

## Calculate Market Capitalization

In [52]:
market_data = prices_on_date[
    ['Ticker', 'SimFinId', 'Close', 'Shares Outstanding']
].copy()

In [53]:
market_data['Market Cap'] = (
    market_data['Close'] * market_data['Shares Outstanding']
)

In [54]:
market_data.head()

     Ticker  SimFinId   Close  Shares Outstanding    Market Cap
1229      A     45846  128.35        2.835004e+08  3.638728e+10
2466     AA    367153   32.89        2.589147e+08  8.515705e+09
2595   AACB  18959140   10.18                 NaN           NaN
3828   AACG  18712193    1.38        6.399578e+07  8.831418e+07
6332   AAGH  12444287    0.00        2.120481e+10  0.000000e+00

In [55]:
market_data['Market Cap'].describe()

count    4.521000e+03
mean     2.082276e+10
std      1.540310e+11
min      0.000000e+00
25%      1.470438e+08
50%      9.331324e+08
75%      5.863158e+09
max      4.533894e+12
Name: Market Cap, dtype: float64

## Select Available Financial Statements

We use only statements published by the valuation date to avoid later publications. Downloaded values may still reflect later restatements, so Publish Date alone does not prove that all values were known at the time. We retain restatement flags to inspect that limitation.

In [56]:
income_available = income[income['Publish Date'] <= valuation_date].copy()

balance_available = balance[balance['Publish Date'] <= valuation_date].copy()

cashflow_available = cashflow[cashflow['Publish Date'] <= valuation_date].copy()

In [57]:
income_available['Fiscal Period'].value_counts()

Fiscal Period
Q1    11975
Q2    11907
Q4    11517
Q3     9967
Name: count, dtype: int64

In [58]:
income_available.duplicated(
    subset=['SimFinId', 'Fiscal Year', 'Fiscal Period']
).sum()

np.int64(0)

## Build TTM Income Variables

In [59]:
income_available = income_available.sort_values(
    ['SimFinId', 'Report Date']
)

In [60]:
income_latest4 = (
    income_available
    .groupby('SimFinId')
    .tail(4)
)

In [61]:
income_latest4.groupby('SimFinId').size().value_counts()

4    2854
1     296
2     230
3     142
Name: count, dtype: int64

In [62]:
income_available = income_available.sort_values(
    ['SimFinId', 'Report Date']
)

income_latest4 = income_available.groupby('SimFinId').tail(4)

income_latest4.groupby('SimFinId').size().value_counts()

4    2854
1     296
2     230
3     142
Name: count, dtype: int64

In [63]:
income_latest4.groupby('SimFinId')['Report Date'].agg(['min', 'max']).head(10)

                min        max
SimFinId
18       2024-09-30 2025-06-30
243      2022-09-30 2023-06-30
914      2023-09-30 2024-06-30
14099    2024-11-30 2025-08-31
22219    2024-09-30 2025-06-30
30388    2021-09-30 2022-06-30
33021    2025-01-31 2025-01-31
34429    2020-12-31 2020-12-31
35151    2024-09-30 2025-06-30
36205    2024-09-30 2025-06-30

We first require exactly four quarters. We then check that fiscal quarters are consecutive and report dates are reasonably spaced; four rows alone do not establish a full year.

In [64]:
quarter_counts = income_latest4.groupby('SimFinId').size()
quarter_counts.value_counts()

4    2854
1     296
2     230
3     142
Name: count, dtype: int64

In [65]:
valid_income_ids = quarter_counts[quarter_counts == 4].index
income_latest4 = income_latest4[income_latest4['SimFinId'].isin(valid_income_ids)].copy()
print('Companies with four income quarters:', income_latest4['SimFinId'].nunique())

Companies with four income quarters: 2854

We require three consecutive fiscal-quarter transitions and allow 60–120 days between reports. This simple spacing rule may exclude unusual reporting calendars that need later review.

In [66]:
income_latest4['Quarter_Number'] = income_latest4['Fiscal Year'] * 4 + income_latest4['Fiscal Period'].str[-1].astype(int)

In [67]:
income_latest4['Quarter_Gap'] = income_latest4.groupby('SimFinId')['Quarter_Number'].diff()
income_latest4['Report_Gap_Days'] = income_latest4.groupby('SimFinId')['Report Date'].diff().dt.days

In [68]:
income_latest4['Valid_Gap'] = (
    (income_latest4['Quarter_Gap'] == 1)
    & (income_latest4['Report_Gap_Days'] >= 60)
    & (income_latest4['Report_Gap_Days'] <= 120)
)
income_valid_gaps = income_latest4.groupby('SimFinId')['Valid_Gap'].sum()
income_valid_gaps.value_counts()

Valid_Gap
3    2851
2       2
1       1
Name: count, dtype: int64

In [69]:
income_consecutive_ids = income_valid_gaps[income_valid_gaps == 3].index
income_latest4 = income_latest4[income_latest4['SimFinId'].isin(income_consecutive_ids)].copy()
print('Companies after quarter-spacing check:', income_latest4['SimFinId'].nunique())

Companies after quarter-spacing check: 2851

In [70]:
income_dates = income_latest4.groupby('SimFinId')['Report Date'].agg(['min', 'max']).reset_index()
income_dates = income_dates.rename(columns={'min': 'Income_First_Report_Date', 'max': 'Income_Latest_Report_Date'})
income_dates.head()

   SimFinId Income_First_Report_Date Income_Latest_Report_Date
0        18               2024-09-30                2025-06-30
1       243               2022-09-30                2023-06-30
2       914               2023-09-30                2024-06-30
3     14099               2024-11-30                2025-08-31
4     22219               2024-09-30                2025-06-30

In [71]:
print('Before income freshness filter:', income_dates.shape[0])
income_dates = income_dates[income_dates['Income_Latest_Report_Date'] >= freshness_cutoff].copy()
print('After income freshness filter:', income_dates.shape[0])

Before income freshness filter: 2851
After income freshness filter: 2219

In [72]:
income_latest4 = income_latest4[income_latest4['SimFinId'].isin(income_dates['SimFinId'])].copy()
income_latest4[['Revenue', 'Operating Income (Loss)']].isnull().sum()

Revenue                    834
Operating Income (Loss)      0
dtype: int64

Each TTM variable needs four nonmissing values. Incomplete totals stay missing instead of representing a partial year.

In [73]:
income_ttm = income_latest4.groupby('SimFinId')[['Revenue', 'Operating Income (Loss)']].sum(min_count=4).reset_index()
income_ttm = income_ttm.rename(columns={'Revenue': 'Revenue_TTM', 'Operating Income (Loss)': 'Operating_Income_TTM'})

In [74]:
income_ttm = income_ttm.merge(income_dates, on='SimFinId', how='left', validate='one_to_one')
income_ttm.head()

   SimFinId   Revenue_TTM  ...  Income_First_Report_Date Income_Latest_Report_Date
0        18  3.713990e+11  ...                2024-09-30                2025-06-30
1     14099  2.318100e+10  ...                2024-11-30                2025-08-31
2     22219  2.460200e+10  ...                2024-09-30                2025-06-30
3     35151  3.651078e+09  ...                2024-09-30                2025-06-30
4     36205  3.332108e+09  ...                2024-09-30                2025-06-30

[5 rows x 5 columns]

In [75]:
income_ttm.shape

(2219, 5)

In [76]:
income_latest4['Restated_After_Valuation'] = income_latest4['Restated Date'] > valuation_date
income_flags = income_latest4.groupby('SimFinId')['Restated_After_Valuation'].max().reset_index()
income_flags = income_flags.rename(columns={'Restated_After_Valuation': 'Income_Restated_After_Valuation'})
income_ttm = income_ttm.merge(income_flags, on='SimFinId', how='left', validate='one_to_one')

## Build TTM Cash Flow Variables

We create cashflow_latest4 before checking its quarter counts. Missing D&A is not replaced with older quarters.

In [77]:
cashflow_available.duplicated(subset=['SimFinId', 'Fiscal Year', 'Fiscal Period']).sum()

np.int64(0)

In [78]:
cashflow_available = cashflow_available.sort_values(['SimFinId', 'Report Date'])
cashflow_latest4 = cashflow_available.groupby('SimFinId').tail(4).copy()

In [79]:
cashflow_counts = cashflow_latest4.groupby('SimFinId').size()
cashflow_counts.value_counts()

4    2854
1     295
2     225
3     147
Name: count, dtype: int64

In [80]:
valid_cashflow_ids = cashflow_counts[cashflow_counts == 4].index
cashflow_latest4 = cashflow_latest4[cashflow_latest4['SimFinId'].isin(valid_cashflow_ids)].copy()
print('Companies with four cash-flow quarters:', cashflow_latest4['SimFinId'].nunique())

Companies with four cash-flow quarters: 2854

In [81]:
cashflow_latest4['Quarter_Number'] = cashflow_latest4['Fiscal Year'] * 4 + cashflow_latest4['Fiscal Period'].str[-1].astype(int)

In [82]:
cashflow_latest4['Quarter_Gap'] = cashflow_latest4.groupby('SimFinId')['Quarter_Number'].diff()
cashflow_latest4['Report_Gap_Days'] = cashflow_latest4.groupby('SimFinId')['Report Date'].diff().dt.days

In [83]:
cashflow_latest4['Valid_Gap'] = (
    (cashflow_latest4['Quarter_Gap'] == 1)
    & (cashflow_latest4['Report_Gap_Days'] >= 60)
    & (cashflow_latest4['Report_Gap_Days'] <= 120)
)
cashflow_valid_gaps = cashflow_latest4.groupby('SimFinId')['Valid_Gap'].sum()
cashflow_valid_gaps.value_counts()

Valid_Gap
3    2851
1       2
2       1
Name: count, dtype: int64

In [84]:
cashflow_consecutive_ids = cashflow_valid_gaps[cashflow_valid_gaps == 3].index
cashflow_latest4 = cashflow_latest4[cashflow_latest4['SimFinId'].isin(cashflow_consecutive_ids)].copy()
print('Companies after quarter-spacing check:', cashflow_latest4['SimFinId'].nunique())

Companies after quarter-spacing check: 2851

In [85]:
cashflow_dates = cashflow_latest4.groupby('SimFinId')['Report Date'].agg(['min', 'max']).reset_index()
cashflow_dates = cashflow_dates.rename(columns={'min': 'Cashflow_First_Report_Date', 'max': 'Cashflow_Latest_Report_Date'})

In [86]:
print('Before cash-flow freshness filter:', cashflow_dates.shape[0])
cashflow_dates = cashflow_dates[cashflow_dates['Cashflow_Latest_Report_Date'] >= freshness_cutoff].copy()
print('After cash-flow freshness filter:', cashflow_dates.shape[0])

Before cash-flow freshness filter: 2851
After cash-flow freshness filter: 2219

In [87]:
cashflow_latest4 = cashflow_latest4[cashflow_latest4['SimFinId'].isin(cashflow_dates['SimFinId'])].copy()
cashflow_latest4['Depreciation & Amortization'].isnull().sum()

np.int64(376)

In [88]:
cashflow_ttm = cashflow_latest4.groupby('SimFinId')[['Depreciation & Amortization']].sum(min_count=4).reset_index()
cashflow_ttm = cashflow_ttm.rename(columns={'Depreciation & Amortization': 'DA_TTM'})
cashflow_ttm = cashflow_ttm.merge(cashflow_dates, on='SimFinId', how='left', validate='one_to_one')

In [89]:
cashflow_ttm['DA_TTM'].isnull().sum()

np.int64(108)

In [90]:
cashflow_latest4['Restated_After_Valuation'] = cashflow_latest4['Restated Date'] > valuation_date
cashflow_flags = cashflow_latest4.groupby('SimFinId')['Restated_After_Valuation'].max().reset_index()
cashflow_flags = cashflow_flags.rename(columns={'Restated_After_Valuation': 'Cashflow_Restated_After_Valuation'})
cashflow_ttm = cashflow_ttm.merge(cashflow_flags, on='SimFinId', how='left', validate='one_to_one')

## Calculate EBITDA

We preserve income companies with missing cash-flow data. We only add D&A when income and cash flow cover the same four-quarter window.

In [91]:
print('Before cash-flow merge:', income_ttm.shape)
ttm_financials = income_ttm.merge(cashflow_ttm, on='SimFinId', how='left', validate='one_to_one')
print('After cash-flow merge:', ttm_financials.shape)

Before cash-flow merge: (2219, 6)
After cash-flow merge: (2219, 10)

In [92]:
ttm_financials['Matching_TTM_Window'] = (
    (ttm_financials['Income_First_Report_Date'] == ttm_financials['Cashflow_First_Report_Date'])
    & (ttm_financials['Income_Latest_Report_Date'] == ttm_financials['Cashflow_Latest_Report_Date'])
)
ttm_financials['Matching_TTM_Window'].value_counts()

Matching_TTM_Window
True     2213
False       6
Name: count, dtype: int64

In [93]:
ttm_financials.loc[~ttm_financials['Matching_TTM_Window'], 'DA_TTM'] = np.nan
ttm_financials['EBITDA_TTM'] = ttm_financials['Operating_Income_TTM'] + ttm_financials['DA_TTM']

In [94]:
ttm_financials['EBITDA_Margin'] = np.nan
nonzero_revenue = ttm_financials['Revenue_TTM'].notnull() & (ttm_financials['Revenue_TTM'] != 0)
ttm_financials.loc[nonzero_revenue, 'EBITDA_Margin'] = (
    ttm_financials.loc[nonzero_revenue, 'EBITDA_TTM']
    / ttm_financials.loc[nonzero_revenue, 'Revenue_TTM']
)

In [95]:
ttm_financials.head()

   SimFinId   Revenue_TTM  ...    EBITDA_TTM EBITDA_Margin
0        18  3.713990e+11  ...  1.390450e+11      0.374382
1     14099  2.318100e+10  ...  9.254000e+09      0.399206
2     22219  2.460200e+10  ...  6.002000e+09      0.243964
3     35151  3.651078e+09  ...  5.029790e+08      0.137762
4     36205  3.332108e+09  ...  6.428770e+08      0.192934

[5 rows x 13 columns]

In [96]:
ttm_financials.shape

(2219, 13)

In [97]:
ttm_financials[['Revenue_TTM', 'Operating_Income_TTM', 'DA_TTM', 'EBITDA_TTM', 'EBITDA_Margin']].describe()

        Revenue_TTM  Operating_Income_TTM  ...    EBITDA_TTM  EBITDA_Margin
count  1.977000e+03          2.219000e+03  ...  2.105000e+03    1926.000000
mean   8.135412e+09          1.020280e+09  ...  1.463525e+09     -13.964689
std    3.546444e+10          6.296473e+09  ...  8.042603e+09     338.075938
min    0.000000e+00         -4.397000e+09  ... -3.153000e+09  -13451.716102
25%    2.414920e+08         -2.128700e+07  ... -7.279000e+06       0.015322
50%    1.064824e+09          4.392100e+07  ...  1.073840e+08       0.121564
75%    4.163735e+09          4.131000e+08  ...  6.670000e+08       0.240829
max    6.931530e+11          1.302140e+11  ...  1.586290e+11       1.224498

[8 rows x 5 columns]

## Select Latest Balance Sheet

Debt and cash measure values at a point in time, so we do not sum four balance sheets. Missing debt remains missing rather than being assumed to equal zero.

In [98]:
balance.columns

Index(['Ticker', 'SimFinId', 'Currency', 'Fiscal Year', 'Fiscal Period',
       'Report Date', 'Publish Date', 'Restated Date',
       'Cash, Cash Equivalents & Short Term Investments', 'Short Term Debt',
       'Long Term Debt', 'Total Assets', 'Total Liabilities', 'Total Equity'],
      dtype='str')

In [99]:
balance_available = balance_available.sort_values(['SimFinId', 'Report Date'])
balance_latest = balance_available.groupby('SimFinId').tail(1).copy()

In [100]:
balance_latest = balance_latest[[
    'SimFinId', 'Report Date', 'Currency', 'Restated Date',
    'Cash, Cash Equivalents & Short Term Investments',
    'Short Term Debt', 'Long Term Debt', 'Total Assets', 'Total Equity'
]].copy()
balance_latest = balance_latest.rename(columns={'Report Date': 'Balance_Report_Date', 'Currency': 'Balance_Currency', 'Restated Date': 'Balance_Restated_Date'})

In [101]:
balance_latest[['Short Term Debt', 'Long Term Debt']].isnull().sum()

Short Term Debt    1707
Long Term Debt     1082
dtype: int64

In [102]:
balance_latest['Total_Debt'] = balance_latest['Short Term Debt'] + balance_latest['Long Term Debt']
balance_latest['Total_Debt'].isnull().sum()

np.int64(1941)

In [103]:
balance_latest['Balance_Is_Stale'] = balance_latest['Balance_Report_Date'] < freshness_cutoff
balance_latest['Balance_Is_Stale'].value_counts()

Balance_Is_Stale
False    2600
True      922
Name: count, dtype: int64

In [104]:
balance_latest['Balance_Restated_After_Valuation'] = balance_latest['Balance_Restated_Date'] > valuation_date
balance_latest.head()

       SimFinId  ... Balance_Restated_After_Valuation
18520        18  ...                            False
4446        243  ...                            False
6331        914  ...                            False
867       14099  ...                            False
27679     22219  ...                            False

[5 rows x 12 columns]

## Merge Financial and Market Data

Left merges retain all companies priced on the valuation date and expose missing financial data. one_to_one validation prevents accidental row multiplication.

In [105]:
print('Market data shape:', market_data.shape)
print('Unique market IDs:', market_data['SimFinId'].nunique())

Market data shape: (4699, 5)
Unique market IDs: 4699

In [106]:
final_data = market_data.merge(ttm_financials, on='SimFinId', how='left', validate='one_to_one')
print('After TTM merge:', final_data.shape)
print('Missing income TTM window:', final_data['Income_Latest_Report_Date'].isnull().sum())

After TTM merge: (4699, 17)
Missing income TTM window: 2742

In [107]:
final_data = final_data.merge(balance_latest, on='SimFinId', how='left', validate='one_to_one')
print('After balance-sheet merge:', final_data.shape)
print('Missing balance sheet:', final_data['Balance_Report_Date'].isnull().sum())

After balance-sheet merge: (4699, 28)
Missing balance sheet: 2202

## Calculate Enterprise Value

We use Market Cap + Total_Debt − Cash. The available cash field includes short-term investments; this simplified EV omits preferred stock and noncontrolling interests. We retain stale balance sheets for inspection but leave EV missing if they are over one year old.

In [108]:
final_data['Enterprise_Value'] = (
    final_data['Market Cap'] + final_data['Total_Debt']
    - final_data['Cash, Cash Equivalents & Short Term Investments']
)
final_data.loc[final_data['Balance_Is_Stale'] == True, 'Enterprise_Value'] = np.nan

In [109]:
income_latest4['Currency'].value_counts(dropna=False)

Currency
USD    8876
Name: count, dtype: int64

In [110]:
cashflow_latest4['Currency'].value_counts(dropna=False)

Currency
USD    8876
Name: count, dtype: int64

In [111]:
final_data['Balance_Currency'].value_counts(dropna=False)

Balance_Currency
USD    2497
NaN    2202
Name: count, dtype: int64

We check currencies before combining U.S. market values with financial statements. Non-USD statements need currency conversion before forming EV/EBITDA.

In [112]:
income_usd_counts = income_latest4[income_latest4['Currency'] == 'USD'].groupby('SimFinId').size()
cashflow_usd_counts = cashflow_latest4[cashflow_latest4['Currency'] == 'USD'].groupby('SimFinId').size()
income_usd_ids = income_usd_counts[income_usd_counts == 4].index
cashflow_usd_ids = cashflow_usd_counts[cashflow_usd_counts == 4].index

In [113]:
final_data['Financials_In_USD'] = (
    final_data['SimFinId'].isin(income_usd_ids)
    & final_data['SimFinId'].isin(cashflow_usd_ids)
    & (final_data['Balance_Currency'] == 'USD')
)
final_data['Financials_In_USD'].value_counts()

Financials_In_USD
False    2742
True     1957
Name: count, dtype: int64

In [114]:
final_data.loc[final_data['Balance_Currency'] != 'USD', 'Enterprise_Value'] = np.nan

## Build Valuation Multiple

Negative EBITDA and unusual multiples remain for inspection. A zero denominator gives a missing multiple instead of infinity.

In [115]:
final_data['EV_EBITDA'] = np.nan
valid_denominator = (
    final_data['EBITDA_TTM'].notnull()
    & (final_data['EBITDA_TTM'] != 0)
    & final_data['Financials_In_USD']
)
final_data.loc[valid_denominator, 'EV_EBITDA'] = (
    final_data.loc[valid_denominator, 'Enterprise_Value']
    / final_data.loc[valid_denominator, 'EBITDA_TTM']
)

In [116]:
final_data[['Enterprise_Value', 'EBITDA_TTM', 'EV_EBITDA']].describe()

       Enterprise_Value    EBITDA_TTM    EV_EBITDA
count      1.052000e+03  1.874000e+03   886.000000
mean       3.679050e+10  1.607959e+09    16.316973
std        1.915603e+11  8.504837e+09   185.259458
min       -7.546554e+10 -3.153000e+09  -838.036752
25%        8.318458e+08 -2.484000e+06     6.942191
50%        4.035606e+09  1.323820e+08    11.125975
75%        1.870535e+10  7.295822e+08    17.185609
max        3.825135e+12  1.586290e+11  5345.107789

In [117]:
final_data[['Enterprise_Value', 'EBITDA_TTM', 'EV_EBITDA']].isnull().sum()

Enterprise_Value    3647
EBITDA_TTM          2825
EV_EBITDA           3813
dtype: int64

In [118]:
print('EBITDA <= 0:', (final_data['EBITDA_TTM'] <= 0).sum())
print('Enterprise value <= 0:', (final_data['Enterprise_Value'] <= 0).sum())
print('EV/EBITDA <= 0:', (final_data['EV_EBITDA'] <= 0).sum())

EBITDA <= 0: 497
Enterprise value <= 0: 7
EV/EBITDA <= 0: 103

## Add Company Information

We keep one Ticker column and fill missing price-data tickers from the company table.

In [119]:
company_info = companies[['SimFinId', 'Ticker', 'Company Name', 'IndustryId', 'Market']].copy()
company_info = company_info.rename(columns={'Ticker': 'Company_Ticker'})
company_info['SimFinId'].duplicated().sum()

np.int64(0)

In [120]:
final_data = final_data.merge(company_info, on='SimFinId', how='left', validate='one_to_one')
print('After company-information merge:', final_data.shape)

After company-information merge: (4699, 35)

In [121]:
missing_ticker = final_data['Ticker'].isnull()
final_data.loc[missing_ticker, 'Ticker'] = final_data.loc[missing_ticker, 'Company_Ticker']
final_data = final_data.drop(columns=['Company_Ticker'])

## Build Simple Regression Variables

EV_EBITDA and EBITDA_Margin are already constructed. Log market cap is defined only for positive market capitalization.

In [122]:
final_data['log_Market_Cap'] = np.nan
positive_market_cap = final_data['Market Cap'] > 0
final_data.loc[positive_market_cap, 'log_Market_Cap'] = np.log(final_data.loc[positive_market_cap, 'Market Cap'])

Revenue growth will be constructed next. Comparable year-over-year TTM growth needs four additional consecutive quarters matched to the current window; we have not checked that history yet.

## Initial Data Quality Check

We have not run regressions or full EDA, winsorized variables, deleted outliers, or removed negative EBITDA.

In [123]:
final_data.shape

(4699, 35)

In [124]:
final_data.head()

  Ticker  SimFinId   Close  ...  IndustryId  Market  log_Market_Cap
0      A     45846  128.35  ...    106001.0      us       24.317485
1     AA    367153   32.89  ...    110004.0      us       22.865178
2   AACB  18959140   10.18  ...    104002.0      us             NaN
3   AACG  18712193    1.38  ...    102006.0      us       18.296411
4   AAGH  12444287    0.00  ...    106002.0      us             NaN

[5 rows x 35 columns]

In [125]:
main_variables = [
    'Market Cap', 'Enterprise_Value', 'Revenue_TTM', 'EBITDA_TTM',
    'EBITDA_Margin', 'EV_EBITDA', 'log_Market_Cap', 'IndustryId'
]
final_data[main_variables].isnull().sum()

Market Cap           178
Enterprise_Value    3647
Revenue_TTM         2931
EBITDA_TTM          2825
EBITDA_Margin       2973
EV_EBITDA           3813
log_Market_Cap       259
IndustryId           105
dtype: int64

In [126]:
final_data[['Market Cap', 'Enterprise_Value', 'Revenue_TTM', 'EBITDA_TTM', 'EBITDA_Margin', 'EV_EBITDA']].describe()

         Market Cap  Enterprise_Value  ...  EBITDA_Margin    EV_EBITDA
count  4.521000e+03      1.052000e+03  ...    1726.000000   886.000000
mean   2.082276e+10      3.679050e+10  ...     -15.301226    16.316973
std    1.540310e+11      1.915603e+11  ...     357.091181   185.259458
min    0.000000e+00     -7.546554e+10  ...  -13451.716102  -838.036752
25%    1.470438e+08      8.318458e+08  ...       0.029698     6.942191
50%    9.331324e+08      4.035606e+09  ...       0.128424    11.125975
75%    5.863158e+09      1.870535e+10  ...       0.246669    17.185609
max    4.533894e+12      3.825135e+12  ...       1.224498  5345.107789

[8 rows x 6 columns]

In [127]:
print('Rows:', final_data.shape[0])
print('Unique SimFinIds:', final_data['SimFinId'].nunique())
print('Duplicate SimFinIds:', final_data['SimFinId'].duplicated().sum())

Rows: 4699
Unique SimFinIds: 4699
Duplicate SimFinIds: 0

In [128]:
print('Missing shares outstanding:', final_data['Shares Outstanding'].isnull().sum())
print('Close <= 0:', (final_data['Close'] <= 0).sum())
print('Shares outstanding <= 0:', (final_data['Shares Outstanding'] <= 0).sum())
print('Market cap <= 0:', (final_data['Market Cap'] <= 0).sum())

Missing shares outstanding: 178
Close <= 0: 82
Shares outstanding <= 0: 1
Market cap <= 0: 81

In [129]:
final_data[['Income_Restated_After_Valuation', 'Cashflow_Restated_After_Valuation', 'Balance_Restated_After_Valuation', 'Balance_Is_Stale', 'Matching_TTM_Window']].sum()

Income_Restated_After_Valuation      1893
Cashflow_Restated_After_Valuation    1895
Balance_Restated_After_Valuation      127
Balance_Is_Stale                      242
Matching_TTM_Window                  1952
dtype: object

Later-restatement flags need review before claiming these values were all known on September 30, 2025. No processed file is exported yet; final_data is available in memory when the notebook is run.